Fix NPE from AppOpsManager.checkPackage.
commit 649313d6ae6c147acd0d747c11a79f71189eb100
Author: George Burgess IV <gbiv@google.com>
Date:   Tue Dec 13 16:12:10 2016 -0800

    Fix potential NULL dereference errors.

    Found by the static analyzer; there were 10, but all of them looked
    like:

    frameworks/base/media/jni/android_mtp_MtpDatabase.cpp:751:39: warning:
    Array access (from variable 'longValues') results in a null pointer
    dereference
        packet.putUInt128(longValues[i]);

    Bug: None.
    Test: Warnings no longer appear.
    Change-Id: I0f41e93922c51563d77b9f58f3f6538688ff2065
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 1bf2734876e7d2a6eb5c53afd652a38a3b506a42
Author: Kazuki Nakayama <kazuki.x.nakayama@sonymobile.com>
Date:   Fri Nov 4 18:57:39 2016 +0900

    ListPopupWindow: Correct a negative height before showing

    Symptom:
    If an application set a negative height to the popup list,
    surfaceflinger is crashed with SIGABRT.

    Root cause:
    WindowManagerService dose not expect negative
    height of ListPopupWindow. If it's negative,
    WindowManagerService set the negative value to GraphicBufferAlloc,
    but GraphicBufferAlloc handle the value as unsigned int,
    then surfaceflinger is crashed with SIGABRT.

    Solution:
    The popup is drawn with 1px height if mDropDownHeight is negative.

    Bug: 33441454

    Change-Id: I5887674d302e567abfe66147de4819cfdf0ef97b
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 5a8b7b341119496a89267bc3dd37a1e583f7ab39
Author: kaiyiz <kaiyiz@codeaurora.org>
Date:   Thu Aug 14 12:33:54 2014 +0800

    Handle IllegalArgumentException

    In some cases startInputInnerLocked() throws
    IllegalArgumentException which needs to be handle

    Change-Id: I315cb46b1d16c2862989cb9c0c10ed6613884522
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 9d6d59fc30b41852da103b442591743eeab4ddd5
Author: Henrik Baard <henrik.baard@sonymobile.com>
Date:   Tue Feb 10 08:26:39 2015 +0100

    Deadlock in PackageInstallerSession

    On rare ocasions deadlock occur between
    AcitityManagerService.getServices(), PackageManagerService.dump()
    and PackageInstallerSession.dispatchSessionFinished()

    Application calling getRunningServices():
    This thread will first take ActivityManagerService.this lock, then
    when checking UID permissions with package manager it wants
    the mPackages lock

    PackageInstaller thread:
    mHandlerCallback takes mLock and executes dispatchSessionFinished()
    which later will wait for ActivityManagerService.this lock to be
    relesed in PendintIntentRecord.sendInner(). (this lock is now held by
    call to getServices()).

    PackageManagerService thread:
    This thread is performing a dump, that could be requested by an
    application or by system. To perform dump it takes mPackages lock
    then later to dump PackageInstallSesssion it needs to hold mLock
    already held by PackageInstaller thread.

    The simplest solution to this deadlock is to modify the callback
    code in PackageInstallerSession. The call dispatchSessionFinished()
    should never be called while holding PackageInstallerSession.mLock,
    so moving this call outside the lock will resolve this problem.

    Change-Id: I545ccedf89ca90077122ac77d22d7aaed0f7f1fb
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 89a74ca598f16ae61381ebc142c528f6ecf778fa
Author: c_yongga <yongga@codeaurora.org>
Date:   Sat Jan 16 15:10:03 2016 +0800

    SettingsLib: java.lang.NullPointerException

    fix it when execute getScanResults() throw NullPointException

    Change-Id: Ifc46288abd4b08836c2bcb1d45a33606a1891e63
    CRs-Fixed:  954617
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 531e7718190df981e85ca06bfdf827b1718d6a3a
Author: riddle_hsu <riddle_hsu@htc.com>
Date:   Fri Apr 15 12:05:06 2016 +0800

    Fix NPE from AppOpsManager.checkPackage.

    Since commit 0fcef84, any application can use below code
    to insert an invalid op record:
        appOpsManager.checkPackage(0, null);

    Use below command will see the invalid record breaks writeState.
      adb shell dumpsys appops write-settings

      Exception occurred while dumping:
      java.lang.NullPointerException: Attempt to invoke virtual method
      'boolean java.lang.String.equals(java.lang.Object)'
      on a null object reference
            at com.android.server.AppOpsService.writeState

    And system server will crash in 30 minutes when saving the xml.

    Change-Id: I6ebd24126f03bda048cc4070d24783887e4164f9
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

Change-Id: If48c50b01a135cd247a3ca4ee15f437481d6c299
Signed-off-by: mydongistiny <jaysonedson@gmail.com>